/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PlayerChoice } from './playerChoice';

export interface GameRound {
  round_number: number;
  choices: { [key: string]: PlayerChoice };
}
