/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Player } from './player';
import { PlayerChoice } from './playerChoice';

export interface Game {
  id?: string;
  start_time?: string;
  end_time?: string | null;
  winner?: Player | null;
  creator_id: string;
  player_ids?: { [key: string]: PlayerChoice };
}
