/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { GameRound } from './gameRound';

export interface Game {
  id?: string;
  start_time?: string;
  end_time?: string | null;
  winner_id?: string | null;
  logs?: Array<string>;
  max_rounds?: number;
  rounds?: Array<GameRound>;
  creator_id: string;
  player_ids?: Array<string>;
}
