/**
 * FastAPI
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Note { 
    name: string;
    note: string;
    id?: string;
    created_at?: string;
    creator_id: string;
    is_encrypted: boolean;
}

