/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Note {
  id?: string;
  created_at?: string;
  name: string;
  creator_id: string;
  note: string;
  is_encrypted: boolean;
  password: string | null;
}
