/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface Player {
  creation_time?: string;
  id?: string;
  name: string;
  wins?: number;
  current_game_id?: string | null;
}
