/**
 * FastAPI
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export type PlayerChoice = 1 | 2 | 3;

export const PlayerChoice = {
  NUMBER_1: 1 as PlayerChoice,
  NUMBER_2: 2 as PlayerChoice,
  NUMBER_3: 3 as PlayerChoice,
};
